### ISSUE TITLE
Mangler dokumentasjon for Enum Tuning 

### ISSUE THREAD

**Issue by simon-cmyk** [ITK-TTK4235/assignment_5#1]
Issue: På grunn av at enumen ikke er kommentert, ødelegges dokumentasjonen på system structen. 
Bare synlig inne i Data structurs -> system
![Screenshot from 2024-02-08 10-15-08](https://github.com/ITK-TTK4235/assignment_5/assets/80280543/f0bbd5f0-9332-4ccf-9596-7e51c6189a32)

![Screenshot from 2024-02-08 10-12-32](https://github.com/ITK-TTK4235/assignment_5/assets/80280543/aaa75aa6-f816-416d-b392-dc2aa8eddaac)

Endres dette funker det igjen, :bowtie:
![Screenshot from 2024-02-08 10-12-06](https://github.com/ITK-TTK4235/assignment_5/assets/80280543/e2f72619-e594-4f5a-95dd-17ae25fe617c)
![Screenshot from 2024-02-08 10-18-40](https://github.com/ITK-TTK4235/assignment_5/assets/80280543/9d11c15d-0249-4de6-ab39-b16514845bcb)
I system.h
![Screenshot from 2024-02-08 10-18-25](https://github.com/ITK-TTK4235/assignment_5/assets/80280543/a3cbe82d-af25-49b5-91c5-a81871c58c14)

**Comment by terjejacobsson** [comment]
Fint at du oppdaget dette, det skal være fikset nå.
